name: forest_logger
description: !BETA VERSION - NOT FOR LIVE OR PROD USAGE!  A package for translations, from api calls. Only use if your backend team can provide the nedded api urls!
version: 0.0.1
homepage: https://dudasmiklos.com/
repository: https://github.com/DudasMiklos/forest_logger
documentation: https://dudasmiklos.com/

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: